version: '3'

services:
  dapr-server:
    image: peerhuang/dapr.server:latest
    restart: always  
    environment:
      - DAPR_HTTP_PORT=62011
      - DAPR_GRPC_PORT=62012
    network_mode: host
      
  dapr-server-dapr:
    image: "daprio/daprd:latest"
    restart: always    
    command: ["./daprd",
      "--app-id", "Dapr-Server",
#      "--app-protocol", "grpc",
      "--app-port", "62010",
      "--dapr-http-port", "62011",      
      "--dapr-grpc-port", "62012", 
      "--metrics-port", "62013",      
      "-components-path", "/Components",
      "-config", "/Configuration/config.yaml"
      ]
    volumes:
      - "/root/.dapr/components/:/Components"
      - "/root/.dapr/:/Configuration"
    network_mode: host

  dapr-test:
    image: peerhuang/dapr.test:latest
    restart: always  
    environment:
      - DAPR_HTTP_PORT=62021
      - DAPR_GRPC_PORT=62022
    network_mode: host 
                  
  dapr-test-dapr:
    image: "daprio/daprd:latest"
    restart: always    
    command: ["./daprd",
      "--app-id", "Dapr-Test",
#      "--app-protocol", "grpc",
      "--app-port", "62020",
      "--dapr-http-port", "62021",      
      "--dapr-grpc-port", "62022", 
      "--metrics-port", "62023",      
      "-components-path", "/Components",
      "-config", "/Configuration/config.yaml"
      ]
    volumes:
      - "/root/.dapr/components/:/Components"
      - "/root/.dapr/:/Configuration"
    network_mode: host  